# 服务端接口
server:
  port: 8110
# 服务名

spring:
  application:
    name: academy-teacher
  # 环境设置：dev test prod
  profiles:
    active: dev
  datasource:
    # mysql 数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${your mysql username}
    password: ${your mysql password}
    url: jdbc:mysql://localhost:3306/db_20210510_edu_core?serverTimezone=GMT%2B8

# 返回json的全局时间模式
# mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 扫描 mapper
  mapper-locations: classpath:com/emaolv/academy/teacher/mapper/xml/*.xml
# Enable swagger
springfox:
  documentation:
    enabled: true

# 设置日志级别
#logging:
#  level:
#    root: ERROR
