# 服务端接口
server:
  port: 8110
# 服务名

spring:
  application:
    name: academy-teacher
  # 环境设置：dev test prod
  profiles:
    active: dev
  datasource:
    # mysql 数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1a!SY!5om8
    url: jdbc:mysql://localhost:3306/db_20210510_edu_core?serverTimezone=GMT%2B8

# 返回json的全局时间模式
# mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# Enable swagger
springfox:
  documentation:
    enabled: true
