server:
  port: 8112
spring:
  application:
    name: academy-vod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
aliyun:
  vod:
    keyid: ${your keyid}
    keysecret: ${your keysecret}
